name: Content Eunoia
favicon: null
layout_spectrum: 0.5844238146673888
typography_spectrum: 0.9797665388323367
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.08189337328076363
  lightness: 0.5418363104108721
  saturation: 0.11539417202584445
  rhythmicContrast: 0.5760152905713767
purpose: []
